### ISSUE TITLE
grunt-cmd-transport@0.4.0 版本有一个报错

### ISSUE THREAD

**Issue by ghost** [spmjs/grunt-cmd-transport#47]
![qq20130930-2](https://f.cloud.github.com/assets/975175/1235361/e70e29c0-29a3-11e3-842e-3a1a7700c57a.png)

从 Github 上安装的 grunt-cmd-transport，版本是 0.4.0，有如下报错：

![qq20130930-3](https://f.cloud.github.com/assets/975175/1235374/311c6784-29a4-11e3-80c5-4c37bf868763.png)]

报错里的 `src/cart` 是一个子模块的目录。

从 NPM 安装的 grunt-cmd-transport 版本为 0.3.0 是 Ok 的，Grunt 配置完全一样。所以猜想可能是 0.4.0 版本有点问题。

``` coffee
transport:
  app:
    options:
      alias: grunt.file.readJSON "etc/spm_alias.json"
      debug: false
    files: [
      {
        expand: true
        cwd: "src"
        src: "**/*"
        dest: "dist/.build/"
      }
    ]
# END transport
```

**Comment by dreamstu** [comment]
@smallsmallwolf 同求字体，谢谢，直接告知名字就好，大家都能看到
