### ISSUE TITLE
关于模板中的空格问题

### ISSUE THREAD

**Issue by uje** [spmjs/grunt-cmd-transport#78]
是否做个配置，去除模板中多余的空格？

**Comment by uje** [comment]
如果一个插件能完成的为啥要用两个插件呢？

**Comment by popomore** [comment]
这里的 html 是会把 html 转成 js，可能跟你想的不一样，所以才问你的需求。

**Comment by uje** [comment]
我的需求是在html转换成js前把空格及注释去掉
